### PR TITLE
Improve file download performance

### PR DESCRIPTION
**Pull request by DelectableMechanisations**
Love this script.
It saved me an awful lot of time writing this from scratch, but it was in need of some love to fix the issues it was having downloading large files.
The Linux Management pack in particular has some large 1.5 GB+ files in it and the 'Invoke-WebRequest' command can't cope with them and errors out. These are well documented problems and are in large part due to poor internal logic in the 'Invoke-WebRequest' command (e.g. files are saved into memory first before being written to the disk).
I've improved file download performance and reliability by using a new function 'Save-WebFile' which uses System.Net.WebClient to download the files.
Now takes 40 minutes instead of several hours previously.
I've also applied some PSScriptAnalyzer recommendations and cleaned up the change log.

### CODE REVIEW

**Comment by slavizh** [comment]
@DelectableMechanisations as I do not deal with SCOM from several years now I have made you a collaborator on the repo in case you want to do these changes on your own.

**Comment by DelectableMechanisations** [comment]
Hi @slavizh, I'm not able to approve my own Pull Request so you or one of the other contributors will have to approve it.
If you'd prefer to avoid all things SCOM then I can cancel the Pull Request and work off my own fork of the project.
I just thought it was such a good script and you've clearly put a lot of effort into this over the years that you deserved to receive my minor updates to bring it up to scratch.
I promise I won't be offended if you turn down my offer :)

**Comment by DamianFlynn** [comment]
Thank you. For continuing to
Work on this script, as Stan mentioned we have not had focus on SCOM for a couple of years so are not currently in a position to validate the changes to the scripts, but trust you will take the care to try your best and we appreciate that. 

Pull has been merged

**Comment by slavizh** [comment]
You can either continue work on this repo or your own. Either is fine. If needed we will approve the pull requests so you can merge.

**Pull request merged**
